### ISSUE TITLE
`did-remount` is not called when derivative changes

### ISSUE THREAD

**Issue by bago2k4** [martinklepsch/derivatives#14]
Hi Martin, i found something that i think it's an issue. When you have a component mounted and something changes a derivative associated with it, you would expect the `did-remount` hook to be called with the old and the new state.
`did-remount` is what Rum calls `componentWillReceiveProps`.
In my tests this doesn't happen but i think it should. Derivatives are props for the component, it should be alerted when they change.

Here is an example:
```clojure
(def app-state (atom 0))

(def drv-spec
  {;; a source with no dependencies
   :app-state     [[] app-state]})

(rum/defcs sample < rum/reactive
  (d/drv :app-state)
  {:did-remount (fn [old-state new-state]
                            ;; this is never called
                            new-state)})
  [s]
  [:button
   {:on-click #(swap! app-state inc)}
    "Increment app-state"])
```

**Comment by martinklepsch** [comment]
Try the below, I think the reason for the component not being updated is that you are not dereferencing the derivative.

```clojure
(def app-state (atom 0))

(def drv-spec
  {;; a source with no dependencies
   :app-state     [[] app-state]})

(rum/defcs sample < rum/reactive
  (d/drv :app-state)
  {:did-remount (fn [old-state new-state]
                  (js/console.log "This should get called")
                   new-state)})
  [s]
  [:div
   [:button
    {:on-click #(swap! app-state inc)}
     "Increment app-state"]
   [:span (pr-str (d/react :app-state))]
```
In the last line we added a call to `d/react` (which is a small wrapper for Rum's `react` function). Unless you render the contents of the derivative in some way there is no reason for the component to re-render.

**Comment by bago2k4** [comment]
Yeah i usually use `drv/react` when i read data inside the render cycle but still no call..

**Comment by martinklepsch** [comment]
@bago2k4 I looked into this more and it seems that this is an issue with Rum. Here's the minimal repro case. Guess it might make sense to open an issue in the Rum repo.
```clojure
(ns rum-remount-test.app
    (:require [rum.core :as rum]))

(rum/defcs remount-test < rum/reactive (rum/local 0 :n)
  {:did-remount (fn [a b]
                  (js/console.log "did-remount")
                  b)}
  [s]
  [:span (rum/react (:n s))
   [:button {:on-click #(swap! (:n s) inc)} "inc"]])

(defn init []
  (rum/mount (remount-test) (. js/document (getElementById "container"))))
```
Let me know if you can confirm this or not.

**Comment by martinklepsch** [comment]
I will close this but if you can get it to work with plain Rum, please let me know!

**Comment by bago2k4** [comment]
@martinklepsch i think your example is not accurate since a local state change shouldn't trigger a `componentWillReceiveProps`.
although i'm ok with closing this for the moment since i could not get `did-remount` to work so can be that Rum is having an issue with it.

Also it depends how you see derivatives: if you consider them part of the internal state of the component than it's ok to not trigger a `did-remount` when they change but since they are external to the component and the change is applied out of the component (usually with an action) i think they should trigger a `did-remount`.

If I can get to the bottom of this, to be verified, Rum issue i'll let you know.

Thanks

**Comment by martinklepsch** [comment]
Hey @bago2k4, I think I see what you mean now. As far as I understand `did-remount` should only be called if the arguments that were passed to the component change.

Fundamentally derivatives are attached to a component and the change comes "from within" and not from outside (via arguments). I hope that clarifies things a bit.

**Comment by bago2k4** [comment]
Yeah this clarifies a bit, although i think there should be a hook that we can call within the component to know when derivatives are about to change or after they changed (both would be better).
Internal component state is changed only from inside the component (or at least it should) so you have full control on before and after each change, for derivatives is not the same thing. Some times is an API call that triggers a change, an async action, in this case you can't know when a change is about to happen.
Something like:
```clojure
{:derivative-will-change   ;; derivative, actual-value, new-value => nil
 :derivative-did-change}   ;; derivative, old-value, actual-value => nil
```
Maybe i can turn this in a feature request :)

**Comment by martinklepsch** [comment]
@bago2k4 I think you should be able to use `will-update` / `did-update` for this kind of thing. You can use the `get-ref` function to retrieve a reference for a given derivative from the state. 

https://github.com/martinklepsch/derivatives/blob/e813f1ddfd7636a5b6371bd4ff5bb75054e28e6c/src/org/martinklepsch/derivatives.cljc#L173-L181
